{% set name = "scikit-multiflow" %}
{% set version = "0.5.3" %}
{% set sha256 = "a720e0d7ad1af3cf1ea7ae2c0d371ec5a924a9db2aa2ba0be8d0ad99daadcfcf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  skip: true  # [py<35]
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - libcblas
    - numpy >=1.14.0
    - scipy >=1.0.0
    - scikit-learn >=0.20
    - sortedcontainers >=1.5.7
    - matplotlib-base >=2.0.0
    - pandas >=0.25.3
    - pytest-runner
  run:
    - python
    - scipy >=1.0.0
    - scikit-learn >=0.20
    - sortedcontainers >=1.5.7
    - matplotlib-base >=2.0.0
    - pandas >=0.25.3

test:
  imports:
    - skmultiflow

about:
  home: https://scikit-multiflow.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A machine learning package for streaming data in Python.

  description: |
    scikit-multiflow is an open-source machine learning package for streaming data.
    It extends the scientific tools available in the Python ecosystem.
    scikit-multiflow is intended for streaming data applications where data is 
    continuously generated and must be processed and analyzed on the go.
    Data samples are not stored, so learning methods are exposed to new data only once.
  doc_url: https://scikit-multiflow.github.io/scikit-multiflow/
  dev_url: https://github.com/scikit-multiflow/scikit-multiflow

extra:
  recipe-maintainers:
    - jacobmontiel
    - smastelini
