{% set name = "scikit-multiflow" %}
{% set version = "0.4.1" %}
{% set sha256 = "ed4f791107cb7f789f0bb0620c50e743a4d397905146a4d06c62eb98607aa101" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [py<35]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - numpy
    - pytest-runner
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >1.0.0
    - scikit-learn >=0.20
    - sortedcontainers >=1.5.7
    - matplotlib >=2.0.0
    - pandas >=0.21.0

test:
  imports:
    - skmultiflow

about:
  home: https://scikit-multiflow.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A machine learning framework for multi-output/multi-label and stream data.'

  description: |
    scikit-multiflow is inspired by MOA, the most popular open source framework for machine learning for data streams,
    and MEKA, an open source implementation of methods for multi-label learning. scikit-multiflow is also inspired on
    scikit-learn, the most popular framework for machine learning in Python. Following the SciKits philosophy,
    scikit-multiflow is an open source machine learning framework for multi-output/multi-label and stream data.
  doc_url: https://scikit-multiflow.github.io/scikit-multiflow/
  dev_url: https://github.com/scikit-multiflow/scikit-multiflow

extra:
  recipe-maintainers:
    - jacobmontiel
