travis:
  secure:
    BINSTAR_TOKEN: e5IoDyFYLmDQpn2rR5q+4QgzbkLrUOOSG2LAmZjA6h5T+xl13tsQPOzz40zdAJOVvMAmRnbkWDK1npI5ELjJALQ2pPbS7/ixzJf8cqf5k9+/DwV0vWSDYziig0tDp6PiAtWlEgg6h5zfx+8j2y6VEwgDU1HsulGXxqTOnKlFkqDHbpxrOkS8nGf8t1IS+idCT1TjNBKrS2JsVStQAhziPnBqTQsOENTwsP/tUlVPacdDKU+K60F9o5qbl/7BoBDT4fWphCbYjRj0HmitLDsuIjx4F7OrgeDpaTD8y2DkHUQEfZ4Vot5WQe1g0Zu32JgtbiE10uPOqXTEmvxfyP1Q1cfbO7HNxz+gL44U4RfT2qcRE2AvayDUMUgJXDIcL3Yq9FrUq2yKnruGqttbfucaXlGhOYlSCkqgUCSqqat7phITejW+FrTQo6306RxOgvh1rEMxwa5GzEoW8oI1vq4VkCOXRoDAYkmxwulczVnXjqYDkFhsUA+Gs/+2hk/fk5Z+aB281J+kaMYgX+3VRf9M7EkfpdE10ZsYNW3TVTNBretdwO3nF0QPmxQ+GvovoRbeviAi57TPUvhvs9HtslBUwOUDssLvjhcgWDh6YcAHliKMqwc2oiSwLlFpPD8/w1gxsR+eIra93M2aurQ82OgaD4WdJTjkUPOirRUzx8Lre0c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: false
